---
name: ci

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: 0 17 * * *

env:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
  GRADLE_SWITCHES: --console=plain --info --stacktrace --warning-mode=all --no-daemon

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ env.GRADLE_SWITCHES }} build
  depchecktest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: ./gradlew build -x test
      # - uses: dependency-check/Dependency-Check_Action@1.1.0
      - uses: dependency-check/Dependency-Check_Action@main
        with:
          project: test
          path: "."
          format: SARIF
          args: >
            --failOnCVSS 7
      - name: upload-sarif-file
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: reports/dependency-check-report.sarif
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: depcheck-report
          path: ${{ github.workspace }}/reports
