---
name: dependency-check

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: 0 17 * * *

env:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
  GRADLE_SWITCHES: --console=plain --info --stacktrace --warning-mode=all

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - name: dependency-check-analyze
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ env.GRADLE_SWITCHES }} dependencyCheckAnalyze
      - name: upload-sarif-file
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: build/reports/dependency-check-report.sarif
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: dependency-check-report
          path: build/reports
