---
name: dispatcher-test

on:
  workflow_dispatch: {}

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        run: |
          curl -H "Authorization: token token_goes_here" \
              -H 'Accept: application/vnd.github.everest-preview+json' \
              "https://api.github.com/repos/slugstack/jsonresume-theme-straightforward/dispatches" \
              -d '{"event_type": "awesomeness", "client_payload": {"foo": "bar"}}'
