---
name: repository-backup
on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 17 * * *

jobs:
  repository-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.S3_REPOSITORY_BACKUPS_ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.S3_REPOSITORY_BACKUPS_SECRET_ACCESS_KEY }}
          MIRROR_TARGET: slugstack-repository-backups/${{ github.repository }}
        with:
          args: --overwrite --remove
